### ISSUE TITLE
Snippets not working for me? 

### ISSUE THREAD

**Issue by douglasrcjames** [LGmatrix13/nextjs-13-snippets#3]
I type `page` and nothing comes up in VSCode Insiders, maybe there is a specific prefix like `njspage` or `njserror`? Regardless I am not sure how to use this plugin! Maybe I am totally using it wrong!

**Comment by 0xmzk** [comment]
+1 from myself as well. After installing there is no indication of the snippets being available. 

VSCode version.
```
Version: 1.78.2 (user setup)
Commit: b3e4e68a0bc097f0ae7907b217c1119af9e03435
Date: 2023-05-10T14:39:26.248Z
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: Yes
```

When attempting to look them up in a 'Snippets Explorer' nothing also comes up.

**Comment by kenbankspeng** [comment]
Under the Runtime Status tab for the Extension, I see: Unknown language in `contributes.next-js-13-snippets.language`. Provided value: javascript, javascriptreact, typescriptreact

This is what I see in packages.json in this repo:
 ```
"contributes": {
    "snippets": [
      {
        "language": "javascript, javascriptreact, typescriptreact",
        "path": "./snippets/snippets.code-snippets"
      }
    ]
  }
```

I suspect this needs to be changed to:
```
"contributes": {
    "snippets": [
      {
        "language": "javascript",
        "path": "./snippets/snippets.code-snippets"
      }, {
        "language": "javascriptreact",
        "path": "./snippets/snippets.code-snippets"
      }, {
        "language": "typescriptreact",
        "path": "./snippets/snippets.code-snippets"
      }
    ]
  }
```

**Comment by kenbankspeng** [comment]
https://code.visualstudio.com/api/language-extensions/snippet-guide

**Comment by kenbankspeng** [comment]
I went into my ~/.vscode/extensions directory and manually made the suggested change in the packages.json code and this extension started working.

**Comment by LGmatrix13** [comment]
@douglasrcjames @0xmzk @kenbankspeng so sorry for being late to this. Updated `package.json` and will update the build on vs marketplace. Thanks all!
